# Use the official Python image as base image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /code

# Copy the current directory contents into the container at /code
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r Code/requirements.txt

# Expose the port Flask runs on
EXPOSE 5000

# Run the application
CMD ["python", "Code/app.py"]
